data:
    name: homo_retina
    data_dir: remote
    image_list: optical_train.txt
    train_size: 150000
    val_size: 2000
    batch_size: 16
    num_workers: 14
    homography:
        difficulty: 0.7
        max_angle: 45
        patch_shape: [768, 768]
    photometric:
        name: lg
model:
    name: two_view_pipeline_dino
    extractor:
        name: extractors.xfeat # extractors.aliked, gluefactory_nonfree.superpoint
        max_num_keypoints: 512
        force_num_keypoints: True
        detection_threshold: 0.01
        nms_radius: 5
        trainable: False
    ground_truth:
        name: matchers.homography_matcher
        th_positive: 3
        th_negative: 3
    matcher:
        name: matchers.lightglue
        filter_threshold: 0.1
        flash: false
        checkpointed: true
        input_dim: 64 #up_id:2,896, up_id:1,1536
    sd_feature:
        img_size: 768
        t: 0
        up_ft_index: 1
        ensemble_size: 8
train:
    seed: 0
    epochs: 50
    log_every_iter: 100
    eval_every_iter: 500
    lr: 2e-4
    lr_schedule:
        start: 25
        type: exp
        on_epoch: true
        exp_div_10: 10
    plot: [5, 'gluefactory.visualization.visualize_batch.make_match_figures']
benchmarks:
    hpatches:
      eval:
        estimator: opencv
        ransac_th: 0.5
